# __init__.py
from .ComfyUIKokoro import NODE_CLASS_MAPPINGS as _KOK_MAP, NODE_DISPLAY_NAME_MAPPINGS as _KOK_DISP
from .KokoroSaveAudioPath import NODE_CLASS_MAPPINGS as _PATH_MAP, NODE_DISPLAY_NAME_MAPPINGS as _PATH_DISP
from .KokoroStringGate import NODE_CLASS_MAPPINGS as _GATE_MAP, NODE_DISPLAY_NAME_MAPPINGS as _GATE_DISP

NODE_CLASS_MAPPINGS = {**_KOK_MAP, **_PATH_MAP, **_GATE_MAP}
NODE_DISPLAY_NAME_MAPPINGS = {**_KOK_DISP, **_PATH_DISP, **_GATE_DISP}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
